### ISSUE TITLE
serverless.ts support

### ISSUE THREAD

**Issue by yehonadav-feel** [Bielik20/nx-plugins#104]
![image](https://github.com/Bielik20/nx-plugins/assets/106315845/67bf4093-92a9-4744-a9d7-745f145cf92a)
it would be great if we can use .ts files instead of yml files

**Comment by yehonadav-feel** [comment]
nvm, it seems to work on a newly created app

**Comment by Bielik20** [comment]
Hi, I was experimenting with `serverless.ts` approach before and my experience is that it doesn't work well in monorepo setup and lacks proper support and development. My suspicion is that it works for the new app, but as soon as you import something from libs it will break again. I don't remember exactly what was the problem (it was more than a year ago) but I remember I gave up on idea of using `serverless.ts`. 

If it really works you can let me know :)

If it doesn't I am afraid it has little to do with this Nx plugin :/
