### ISSUE TITLE
Linting fails on brand new serverless app

### ISSUE THREAD

**Issue by MelvinVermeer** [Bielik20/nx-plugins#13]
When creating a brand new application and running `npm run lint my-app-name` i get the following linting error.

>  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: apps/my-app-name/jest.config.js.
The file must be included in at least one of the projects provided

### Reproduction

run the following steps from your favourite command line tool

```
npx create-nx-workspace --name=sample --preset=empty --nx-cloud=false
cd sample
npm i
npm i -D @ns3/nx-serverless
nx generate @ns3/nx-serverless:app my-app-name
npm run lint my-app-name
```

**Comment by Bielik20** [comment]
Thank you for finding that issue. I have missed that (I have `jest.config.js` ignored from linting).
I have added linting to e2e test and created PR with fix.
