### ISSUE TITLE
limitations in serverless

### ISSUE THREAD

**Issue by crodriguez-transformd** [Bielik20/nx-plugins#44]
hi, i have being trying to run `serverless offline start` using this plugin but i cant find the way and is important because without `start` serverless-dynamdb-local is not starting

what can we do ? 

after check
https://github.com/Bielik20/nx-plugins/blob/master/packages/nx-serverless/src/executors/serve/executor.ts
and
https://github.com/Bielik20/nx-plugins/blob/f59b68ebd69e976591cf6e058f2107eef3f9b960/packages/nx-core/src/utils/stringify-args.ts

seems to be a limitation because if i add the param will be added as `--start`

**Comment by Bielik20** [comment]
Hello, I would recommend using this executor: https://github.com/Bielik20/nx-plugins/blob/f59b68ebd69e976591cf6e058f2107eef3f9b960/packages/nx-serverless/src/executors/sls/executor.ts#L8-L32

In here you can just pass `command` as a string. It is actually preferred way now, as the old ones are deprecated:
https://github.com/Bielik20/nx-plugins/blob/f59b68ebd69e976591cf6e058f2107eef3f9b960/packages/nx-serverless/src/executors/serve/executor.ts#L12

I didn't provide migrations (sorry, don't have time to write them), but the simplest way to change is to probably generate a new project and simply adjust the old one. But the change is only to `project.json` file, and you should get something like that: https://github.com/Bielik20/nx-plugins/blob/f59b68ebd69e976591cf6e058f2107eef3f9b960/packages/nx-serverless/src/generators/application/generator.spec.ts#L26-L91

**Comment by crodriguez-transformd** [comment]
@Bielik20 thank you for your suggestion, not sure if we should keep this ticket open or not, but i will suggest to also update the executor that i reported

this solved my issue at least
