### ISSUE TITLE
serverless deploy fails with E2BIG error

### ISSUE THREAD

**Issue by kenleytomlin** [Bielik20/nx-plugins#54]
Hi,

Thanks for these great nx extensions. I'm currently running into an issue on the latest v3 of the nx-serverless executors.
```
> nx run core-sitemap:package

Running: npx sls package

 >  NX   Command failed with E2BIG: npx sls package

   spawn E2BIG
   Pass --verbose to see the stacktrace.
```

When running with verbose I get the following

```
Error: Command failed with E2BIG: npx sls package --stage=staging
spawn E2BIG
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:700:9)
    at execa (/home/circleci/repo/node_modules/execa/index.js:83:26)
    at Function.module.exports.command (/home/circleci/repo/node_modules/execa/index.js:230:9)
    at /home/circleci/repo/node_modules/@ns3/nx-serverless/src/executors/sls/executor.js:19:36
    at Generator.next (<anonymous>)
    at /home/circleci/repo/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/circleci/repo/node_modules/tslib/tslib.js:114:16)
    at runExecutor (/home/circleci/repo/node_modules/@ns3/nx-serverless/src/executors/sls/executor.js:11:20)
```

nx version 14.4.3
node v16.15.1
npm 8.11.0

**Comment by Bielik20** [comment]
Hello, I haven't tested it with the newest version of `nx` and `serverless`. Can you point which version introduced this regression?

I don't have that much time on my hands right now, so I doubt I will be able to look into it "soon". I _may_ find some time next week but make no promises. If you want to explore on your own, I always welcome PRs ;)

**Comment by kenleytomlin** [comment]
@Bielik20
I went from nx version 14.1.1 -> 14.4.3
I went from @ns3/nx-serverless version 1.1.2 -> 3.0.0

I've read issues in the nx repository which talk about the affected command returning a E2BIG error. However these were fixed by adding some additional directories to gitignore. I've tried this and have had no luck so far. Interestingly when I debug via ssh in the circle ci environment I can run the individual sls package command without encountering this error.

**Comment by swinarta** [comment]
@kenleytomlin @Bielik20 I have the same problem and it only happened when I run npx sls package in linux machine.
My suspicion is at this particular line: https://github.com/Bielik20/nx-plugins/blob/8c518451b5d72c2410bf3ff9665b1fe9cd47deea/packages/nx-serverless/src/executors/sls/executor.ts#L28.

execa spawn a new child process with a huge args/envs from [NX_CONTEXT_KEY]: JSON.stringify(context) and causes Linux to throw E2BIG error (Argument list too long).

@Bielik20 is it safe to comment this line out?

**Comment by Bielik20** [comment]
Hey, it is not actually, but I am very grateful for that comment. Tomorrow I will be updating Nx and Serverless at work and we face the same problem, so I will definitely look into it.

**Comment by Bielik20** [comment]
Fixed: https://github.com/Bielik20/nx-plugins/pull/57

Thank you all for feedback, it was very helpful 🙇

**Comment by swinarta** [comment]
hi @Bielik20, I can confirm the fix is working 🥳 🥳 🥳  
Thank you for the fast response. Much appreciated.
