### ISSUE TITLE
Error when running 

### ISSUE THREAD

**Issue by TASimpson** [Bielik20/nx-plugins#58]
I am setup using the nx monorepo and angular. I followed the steps and did the following (since there was already by default the ui-e2e cypress tests when adding my initial project) 

1. Removed the existing `ui-e2e` from `angular.json` to avoid conflicts

2. Ran `npm i -D @ns3/nx-jest-playwright`

3. Ran `nx generate @ns3/nx-jest-playwright:project ui-e2e --project ui`

4. Ran `nx run ui-e2e:e2e` and get the following error after it successfully compiled: 

![image](https://user-images.githubusercontent.com/11613404/191293717-2992e537-3214-4019-bded-b86307cecd5c.png)

Please help! Thank you!

**Comment by envil** [comment]
Got the same issue, I was able to fix it by updating the version of `jest-playwright-preset` to:

```
"jest-playwright-preset": "^2.0.0",
```

The old version has different interface to interact with Jest thus it failed to run the tests.
