### ISSUE TITLE
cannot generate nx-jest-playwright project when ran with yarn

### ISSUE THREAD

**Issue by JessnarStretchSense** [Bielik20/nx-plugins#60]
I have a project that uses `yarn` as the main package manager. I was trying to run the command `yarn nx generate @ns3/nx-jest-playwright:project --project myproject-e2e myproject` but I end up getting an error saying `Cannot set properties of undefined (setting 'he2-electron-e2e')`. Am I missing anything?

**Comment by Bielik20** [comment]
May be related: https://github.com/Bielik20/nx-plugins/issues/58

I did not update playwright in here for some time now newer versions of @nrwl/jest may be incompatible. Let me know if updating helped.
