### ISSUE TITLE
execa.command is not a function

### ISSUE THREAD

**Issue by castleadmin** [Bielik20/nx-plugins#62]
Hi, I'm getting the following error when I try to execute 'deploy' and similar commands on the apps:

`execa.command is not a function`

I tried to install version 5 of execa, which removes the error above but leads to another error:

` Command failed with ENOENT: npx sls package`

According to the package.json of the @ns3/nx-serverless package version 1 of execa is required, but according to the github package.json version 5 is the right one.

```
{
  "name": "@ns3/nx-serverless",
  "version": "3.2.0",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/Bielik20/nx-plugins"
  },
  "publishConfig": {
    "access": "public"
  },
  "main": "index.js",
  "generators": "./generators.json",
  "executors": "./executors.json",
  "types": "./index.d.ts",
  "dependencies": {},
  "peerDependencies": {
    "fs-extra": "9.1.0",
    "lodash": "4.17.21",
    "@ns3/nx-core": "^3.2.0",
    "bestzip": "2.2.1",
    "glob": "7.1.4",
    "execa": "1.0.0",
    "chalk": "4.1.0"
  }
}
```

**Comment by Bielik20** [comment]
You are right. I think there is a problem with Nx build executor in this version. I will update Nx. It should work fine then.

**Comment by Bielik20** [comment]
Feel free to reopen if issue persists ;)
