### ISSUE TITLE
nx-serverless executors don't work with pnpm

### ISSUE THREAD

**Issue by ALMaclaine** [Bielik20/nx-plugins#67]
I'm using pnpm and the plugin crashes when running executors because of the specific use of npx:

https://github.com/Bielik20/nx-plugins/blob/master/packages/nx-serverless/src/executors/sls/executor.ts#L21

https://www.npmjs.com/package/detect-package-manager can help.

I'll put up a PR, but I don't know how to test plugins.

**Comment by ALMaclaine** [comment]
I tested changing `npx` to `pnpx` within install in node_modules and it fixes error.

**Comment by Bielik20** [comment]
Yeah, that is my mistake. I think Nx has helper method to detect package manager. You can use it. e2e tests should test happy scenario that nothing breaks. Then we can merge it and you can confirm it works 👍 

If you want to test it yourself you can play with the repository generated by e2e tests. You can run them locally and then in `tmp` folder there will be an Nx repo created for the purpose of testing. You can `cd` there, remove `package-lock.json` or `yarn.lock` (I don't remember what is used there) and then try `pnpm`.

I am on vacation right now so I am respond with a delay, but I will get back to this issue ;)

**Comment by Bielik20** [comment]
I see. I will leave this issue open as more people may be interested in pnpm support. We can pick it up after pnpm issues are resolved ;)

**Comment by ALMaclaine** [comment]
@Bielik20

I've done some more investigating and it seems like pnpm only doesn't work with serverless-webpack.

serverless-esbuild does work with pnpm. I think putting in the change to work with pnpm/yarn may be appropriate at this stage

**Comment by ALMaclaine** [comment]
My previous tests we're using `sls` directly with pnpm install. It seems that's the only way it will work with pnpm.

`pnpm sls` `pnpm dlx sls` and `pnpx sls` all don't work.

I changed the executor to:
```js
const fullCommand = `sls ${command} ${stringifiedArgs}`.trim();
````

Dropping the `npx` and this seems to work, I know this may change dependency requirements but makes everything work with pnpm.

**Comment by Bielik20** [comment]
We could probably use `detectPackageManager` from `nrwl` and in case of `pnpm` just use empty string.

**Comment by ALMaclaine** [comment]
@Bielik20 sounds good to me, would you like me to make a PR?

**Comment by Bielik20** [comment]
Yeah, I don't like to suggest implementation but (sometimes I cannot help myself 😅) I think utility function `getSlsCommand` (`packages/nx-serverless/src/utils/get-sls-command.ts`) that returns:
* for `pnpm ` - `sls`
* for `npm` - `npx sls`
* for `yarn` - `npx sls`/`yarn sls` (this one needs additional testing, currently it works fine with `npx`) 

would be a clean solution 👍

**Comment by ALMaclaine** [comment]
pr up
