### ISSUE TITLE
@nrwl/nx context not found.

### ISSUE THREAD

**Issue by Destreyf** [Bielik20/nx-plugins#75]
I am running into an issue when trying to perform invoke local with a s3 event payload:

```
Error: @nrwl/nx context not found. This is probably because you are running serverless outside nx command.
    at NxFacade (<directory>/packages/nx-serverless/plugin/nrwl/nx-facade.ts:51:13)
    at NxServerlessPlugin.prepare (<directory>/packages/nx-serverless/plugin/index.ts:68:16)
    at NxServerlessPlugin.<anonymous> (<directory>/packages/nx-serverless/plugin/index.ts:32:40)
    at Generator.next (<anonymous>)
    at <directory>/node_modules/@ns3/nx-serverless/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (<directory>/node_modules/@ns3/nx-serverless/node_modules/tslib/tslib.js:111:16)
    at before:invoke:local:invoke (<directory>/packages/nx-serverless/plugin/index.ts:31:48)
    at PluginManager.runHooks (<directory>/node_modules/serverless/lib/classes/plugin-manager.js:530:15)
    at PluginManager.invoke (<directory>/node_modules/serverless/lib/classes/plugin-manager.js:563:20)
    at async PluginManager.run (<directory>/node_modules/serverless/lib/classes/plugin-manager.js:604:7)
    at async Serverless.run (<directory>/node_modules/serverless/lib/serverless.js:179:5)
    at async <directory>/node_modules/serverless/scripts/serverless.js:812:9
```

Output from before the error:
```
> nx run serverless:sls --command invoke local -f import-users-csv -p test.json

Running: npx sls invoke local -f import-users-csv -p test.json
(node:77594) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
Warning: "@ns3/nx-serverless/plugin" is experimental and can change without a major release.
Environment: darwin, node 16.19.0, framework 3.27.0 (local), plugin 6.2.3, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
```

**Comment by Destreyf** [comment]
After switching from `@ns3/nx-serverless/plugin` to `serverless-bundle` the test payload appears to work correctly.

**Comment by Bielik20** [comment]
Hello, yeah, I know what the problem is. `sls` target doesn't have `buildTarget` defined. If you add it (copy from `serve` target for example) it will work. It is actually by design to not make any assumptions about `buildTarget` when running `sls` which can do all sort of things. If you use `invoke local` a lot, I would recommend simply adding that target to your `project.json` with proper (desired) `buildTarget`.

Let me know if it worked for you, and this issue if it did ;)

**Comment by Destreyf** [comment]
@Bielik20 This is exactly what I needed to know!

Setting the build target on SLS does solve it, but I'll leave it out for now because as you mentioned SLS is used for more than just running things.

I created a new `invoke` target, as you mentioned copying from the `serve` target and I was able to get it working.

```json
    "invoke": {
      "executor": "@ns3/nx-serverless:sls",
      "options": {
        "command": "invoke local",
        "buildTarget": "serverless:build"
      }
    }
```

I'm not exactly sure why, but when using my invoke target I have to use the full argument names instead of the abbreviated ones.

To get the invoke target to work correctly (instead of SLS) I had to swap my command to this:
```bash
nx run serverless:invoke --function import-users-csv --path test.json
```

The version that did not work was as follows:
```bash
nx run serverless:invoke -f import-users-csv -p test.json
```

It would convert my args from `-f` and `-p` to `--f` and `--p` which are not proper values/args.  It's easy enough to work around if you know it's happening.

I should probably familiarize myself more with the nx platform as I'm going to guess this happens from their command runners.

**Comment by Bielik20** [comment]
About the flags, yeah, this happens here:
https://github.com/Bielik20/nx-plugins/blob/d48e0ba3f8eed24cbcaab3a935bebe4465a8efdf/packages/nx-serverless/src/executors/sls/executor.ts#L18-L21

It is not super easy to guess if the initial value was a shorthand or a full flag name :(

**Comment by Bielik20** [comment]
For anyone stumbling on that issue later. Shorthand flags should be supported after #81 is merged. Related commit: https://github.com/Bielik20/nx-plugins/pull/81/commits/26a566c243c655e752abf2e8f09a4f06d42d0b21
