### ISSUE TITLE
Rerun release script

### ISSUE THREAD

**Issue by Destreyf** [Bielik20/nx-plugins#77]
It looks like the release script didn't finish due to some errors with rate limiting, I think github was having some issues during this time.

[Job Link](https://github.com/Bielik20/nx-plugins/actions/runs/4210885222/jobs/7308859472)

You should be able to just re-run this job and have it work.

I'm guessing this is what is used to push to NPM but I haven't looked too closely.

**Comment by Bielik20** [comment]
Yeah, this happens a lot at work too when there are many issues to cover, but the most important parts of release completed though so there is no need to worry:
* releasing actual packages
* marking release on github
