### ISSUE TITLE
How to run custom commands ?

### ISSUE THREAD

**Issue by Rafael-rgsousa** [Bielik20/nx-plugins#84]
How can I run custom commands like passing events?

For example: in a project, without nx and this plugin I am able to run something like

serverless invoke local --function FUNCTION_NAME -p PATH_TO_FUNCTION_REQUEST_EVENT.json (a JSON object with a request event properties: queryParams, body, headers, etc) --stage ENV 

How can I run it now on an nx repository with this plugin ?

I tried something like:

npx nx run FUNCTION_PROJECT:sls --command serverless invoke --function FUNCTION_NAME -p PATH_TO_FUNCTION_REQUEST_EVENT.json

It is not working

Can someone please give me some help on it?

Thanks

**Comment by Bielik20** [comment]
Put full command in quotation marks:
```
--command "serverless invoke --function FUNCTION_NAME -p PATH_TO_FUNCTION_REQUEST_EVENT.json"
```

Remember that if you are using experimental plugin you need build target set as well. More info: https://github.com/Bielik20/nx-plugins/issues/75

Please close issue if everything is clear ;)
