### ISSUE TITLE
Cannot find sls when using pnpm

### ISSUE THREAD

**Issue by mmjmanders** [Bielik20/nx-plugins#90]
I'm using the latest version of pnpm (8.6.2 at the time of writing) and using the `@ns3/nx-serverless@4.2.0` plugin in combination with `nx@16.3.2`.

When running `pnpm exec nx run layers:package` (`layers` is a serverless app created with `nx g @ns3/nx-serverless:app`). Then I get the following error:
```shell
> nx run layers:package

Running: sls package

 >  NX   Command failed with ENOENT: sls package

   spawn sls ENOENT
   Pass --verbose to see the stacktrace.


 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target package for project layers and 1 task(s) they depend on (4s)

    ✖    1/2 failed
    ✔    1/2 succeeded [0 read from cache]
```

which is basically saying that `sls` command does not exist.

When running `npx nx run layers:package` it works as expected.

**Comment by Bielik20** [comment]
Hmm, I do not use `pnpm` personally but there was a similar issue some time ago and PR that tried to address it: https://github.com/Bielik20/nx-plugins/issues/67

Maybe it should be revisited with `pnpm exec`. Could you tests it and provide PR with the fix?
