### ISSUE TITLE
Include @nx/devkit as a dependency

### ISSUE THREAD

**Issue by isaacplmann** [Bielik20/nx-plugins#94]
The nx-serverless, nx-jest-playwright and nx-playwright plugins don't have an Nx version listed in the [Nx Plugin Registry](https://nx.dev/extending-nx/registry) because the plugins don't include `@nx/devkit` as a dependency.  Could you please release a version that fixes that?

Thanks,
Isaac (Nx Team)

**Comment by Bielik20** [comment]
Hmm, one of the features of using Nx is that I do not have to manually update package json in individual projects. I would expect `@nx/devkit` to be automatically added in the plugin build process. Still, of course I would be happy to help. Could you point me to the documentation how does `@nx/devkit` ties with the supported Nx version and how to best handle it? I have seen some plugins have ranges, it is not clear to me how to define it.

**Comment by isaacplmann** [comment]
You just need to add `@nx/devkit` in the dependencies with the version of Nx that you're using.  We have a script that will look up your specified `@nx/devkit` version and use the `nx` range that is specified in that version of `@nx/devkit`.

So if you include `"@nx/devkit": "16.3.2"`, what will show up on the plugin registry is `Nx >= 15 <= 17`.  Because `@nx/devkit@16.3.2` has that as a `peerDependency`.

**Comment by Bielik20** [comment]
I am trying to add necessary changes in #95 but there are many problems:
* `@nx/dependency-checks` behaves differently on my machine and on GitHub Actions
* https://github.com/nrwl/nx/issues/18504 causes tests to fail (rightly so)

I will probably wait for a more stable version of Nx to continue with the work.

**Comment by Bielik20** [comment]
@isaacplmann Released, let me know if everything works as expected ;)
